# Overview

Title of project:  "Plastic in the Urban Freshwater Environment"

Name of project author(s): Amelia M. Foley

Name of project reviewer: Alexandra Gil


# Instructions

Write your comments and feedback below for each section/component of the project. The goal should be to help the author improve their project. Make comments as constructive and actionable as possible. You can provide both criticism and praise.

For each component, pick one summary statement by deleting the ones that do not apply and keeping only the one that you think most closely summarizes a given component. 

Make sure your final document compiles/knits into a readable, well-formatted html document.

Delete any sections/text of this template that are not part of your final review document. (Including these instructions.)


# Specific project content evaluation
Evaluate the different parts of the project by filling in the sections below.


## Background, Context and Motivation
How well is the context of the project described? Is a comprehensive background, including summary of previous/related work given? Is the project well placed into the context of existing work (including proper referencing of existing work). Is it clear why the project was undertaken and what new information it hopes to provide?

### Feedback and Comments
Solid background, well conceptualization.The summary and background provided a complete context about the current issue with microplastic pollution. Solid background, well conceptualization. The way that you describe analysis is really detailled. 

### Summary assessment (PICK ONE, DELETE THE OTHERS)

* strong contextualization and motivation


## Question description
How well and clear are the question(s)/hypotheses the project aims to address described? Is it clear how the questions relate to the data?


### Feedback and Comments

The analysis includes multiple questions, those are clear and the data set is clearly oriented to solve the question. Good Job!

### Summary assessment

* question/hypotheses fully clear


## Data description
How well is the data overall described? Is the source provided? Is a codebook or other meta-information available that makes it clear what the data is? 

### Feedback and Comments

The data is well described. Every data source was explained clearly. A codebook was not included but the information provided for every data set makes it clear.

### Summary assessment

* source and overall structure of data well explained


## Data wrangling and exploratory analysis
How well is the data cleaned/processed and explored? Are all steps reasonable and well explained? Are alternatives discussed and considered? Are meaningful exploratory results shown (e.g. in the supplementary materials)?

### Feedback and Comments

Exploration.Rmd shows a good exploration of your data. I really like the way that you go analyzed every plot and explain the reasons that you toke in consideration for performed the exploration.
I really like the way that you present the correlation, it was the easiest way to clearly see the correlation between the amount of variables that you have. Other plots were very clear too.

### Summary assessment

* essentially no weaknesses in wrangling and exploratory component


## Appropriateness of Analysis
Were the analysis methods appropriate for the data? Was the analysis done properly? Were different components of the analysis (e.g. performance measure, variable selection, data pre-processing, model evaluation) done in the best way possible and explained well?

### Feedback and Comments
The analysis was very extructured. The model evaluation with turbidity - linear regression shows better performance base on the RMSE

### Summary assessment

* strong and reasonable analysis

## Presentation
How well are results presented? Are tables and figures easy to read and understand? Are the main figures/tables publication level quality? 

### Feedback and Comments

The analysis presents a good amount of plots and tables for present the outcomes.
The visualization was good, and consistend according with the analysis. 

### Summary assessment

* results are very well presented


## Discussion/Conclusions
Are the study findings properly discussed? Are strengths and limitations acknowledged? Are findings interpreted properly?

### Feedback and Comments

The discussion/conclusion is base on the outcomes, showing that the data set an the way that the analysis was performed answer the questions of the project.

### Summary assessment

* strong, complete and clear discussion


## Further comments

_Add any other comments regarding the different aspects of the project here. Write anything you think can help your classmate improve their project._



# Overall project content evaluation
Evaluate overall features of the project  by filling in the sections below.


## Structure
Is the project well structured? Are files in well labeled folders? Do files have reasonable names? Are all "junk" files not needed for analysis/reproduction removed? By just looking at files and folders, can you get an idea of how things fit together?

### Feedback and Comments

Overall the project is well structured, there is not unused files. However, it would be beneficial includes the best way to start running the code. 

### Summary assessment

* well structured


## Documentation 
How well is the project documented? Are you able to understand each step of the whole analysis, each decision that was made, and each line of code? Is enough information provided as comments in code or as part of Rmd files? 

### Feedback and Comments

The documentation around every script was clear and very informative. I like the way you describe the outcomes and the way that you will try to solve issues. 

### Summary assessment

* fully and well documented


## Reproducibility
Are all results fully reproducible? Is documentation provided which clearly explains how to reproduce things, and does it work without the need for any manual intervention? Are you able to re-run the whole analysis without having to do manual interventions/edits?

### Feedback and Comments

- Since you included so many processing codes, could be a good idea includes the best way to start the running the code. This could be described in README portion.

- Unfortunately for my, I couldn't reproduced the LASSO modeling. My R aborted multiple time. But this is not anything wrong with your code...After multiple intents even in homeworks I conclude that is something associate with my laptop.


### Summary assessment

* fully reproducible without issues


## Thoroughness
How thorough was the overall study? Were alternatives (e.g. different ways of processing the data or different models) considered? Were alternatives discussed? Were the questions/hypotheses fully and thoroughly addressed?

### Feedback and Comments

The way that you structure your project was very detailed. For modeling portion the analysis includes LASSO, Decision Tree, and Random Forest. The plot model_grid.png was a amazing idea! Good Job :)

### Summary assessment

* strong level of thorougness


## Further comments

Good Job! in my opinion this is a good topic well analyzed, because so many areas were analyzed.




